/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unicauca.figures.presentation;

import com.unicauca.figures.domain.model.Circle;

/**
 *
 * @author 
 */
public class GUICircle extends javax.swing.JFrame {
    
     private Circle circle;
     
    /**
     * Creates new form GUICIRCLE2
     */
    public GUICircle() {
        initComponents();
        circle = new Circle(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnRegresarMenuCirculo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelFormularioCirculo = new javax.swing.JPanel();
        lblRadius = new javax.swing.JLabel();
        txtRadius = new javax.swing.JTextField();
        lblAreaCircle = new javax.swing.JLabel();
        txtAreaCircle = new javax.swing.JTextField();
        lblPerimeterCircle = new javax.swing.JLabel();
        txtPerimeterCircle = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular);

        btnRegresarMenuCirculo.setText("Regresar Menu");
        btnRegresarMenuCirculo.setActionCommand("Regresar Menú");
        btnRegresarMenuCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuCirculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarMenuCirculo);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Círculo");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanelFormularioCirculo.setLayout(new java.awt.GridLayout(3, 2));

        lblRadius.setText("Radio");
        jPanelFormularioCirculo.add(lblRadius);
        jPanelFormularioCirculo.add(txtRadius);

        lblAreaCircle.setText("Area");
        jPanelFormularioCirculo.add(lblAreaCircle);
        jPanelFormularioCirculo.add(txtAreaCircle);

        lblPerimeterCircle.setText("Perimetro");
        jPanelFormularioCirculo.add(lblPerimeterCircle);
        jPanelFormularioCirculo.add(txtPerimeterCircle);

        getContentPane().add(jPanelFormularioCirculo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try{
            double radius = Double.parseDouble(txtRadius.getText());
            if(radius <= 0){
                txtAreaCircle.setText("Radio debe ser mayor a 0");
                txtPerimeterCircle.setText("Radio debe ser mayor a 0");
            }else{
                circle.setRadius(radius);
                txtAreaCircle.setText("" + circle.calculateArea());
                txtPerimeterCircle.setText("" + circle.calculatePerimeter());
            }
            
        }catch(NumberFormatException e){
            txtAreaCircle.setText("Tipo de dato no válido");
            txtPerimeterCircle.setText("Tipo de dato no válido");
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnRegresarMenuCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuCirculoActionPerformed
        GUIMenu abrir = new GUIMenu();
        abrir.setVisible(true);
        this.setVisible(false);     
    }//GEN-LAST:event_btnRegresarMenuCirculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICircle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICircle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICircle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICircle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICircle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnRegresarMenuCirculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFormularioCirculo;
    private javax.swing.JLabel lblAreaCircle;
    private javax.swing.JLabel lblPerimeterCircle;
    private javax.swing.JLabel lblRadius;
    private javax.swing.JTextField txtAreaCircle;
    private javax.swing.JTextField txtPerimeterCircle;
    private javax.swing.JTextField txtRadius;
    // End of variables declaration//GEN-END:variables
}
