/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unicauca.figures.presentation;

import com.unicauca.figures.domain.model.Square;

/**
 *
 * @author Laura Sofia
 */
public class GUISquare extends javax.swing.JFrame {

    private Square square;
    /**
     * Creates new form GUISquare
     */
    public GUISquare() {
        initComponents();
        square = new Square(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        JLabelCuadrado = new javax.swing.JLabel();
        jPanelbuttonsCuadrado = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnRegresarMenuCuadrado = new javax.swing.JButton();
        jPanelFormularioCuadrado = new javax.swing.JPanel();
        lblLadoCuadrado = new javax.swing.JLabel();
        txtLadoCuadrado = new javax.swing.JTextField();
        lblAreaCuadrado = new javax.swing.JLabel();
        txtAreaCuadrado = new javax.swing.JTextField();
        lblPerimetroCuadrado = new javax.swing.JLabel();
        txtPerimetroCuadrado = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabelCuadrado.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        JLabelCuadrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelCuadrado.setText("CUADRADO");
        getContentPane().add(JLabelCuadrado, java.awt.BorderLayout.PAGE_START);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanelbuttonsCuadrado.add(btnCalcular);

        btnRegresarMenuCuadrado.setText("Regresar Menu");
        btnRegresarMenuCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuCuadradoActionPerformed(evt);
            }
        });
        jPanelbuttonsCuadrado.add(btnRegresarMenuCuadrado);

        getContentPane().add(jPanelbuttonsCuadrado, java.awt.BorderLayout.PAGE_END);

        jPanelFormularioCuadrado.setLayout(new java.awt.GridLayout(3, 2));

        lblLadoCuadrado.setText("Lado");
        jPanelFormularioCuadrado.add(lblLadoCuadrado);
        jPanelFormularioCuadrado.add(txtLadoCuadrado);

        lblAreaCuadrado.setText("Area");
        jPanelFormularioCuadrado.add(lblAreaCuadrado);
        jPanelFormularioCuadrado.add(txtAreaCuadrado);

        lblPerimetroCuadrado.setText("Perimetro");
        jPanelFormularioCuadrado.add(lblPerimetroCuadrado);
        jPanelFormularioCuadrado.add(txtPerimetroCuadrado);

        getContentPane().add(jPanelFormularioCuadrado, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try{
            double lado = Double.parseDouble(txtLadoCuadrado.getText());
            if(lado <= 0){
                txtAreaCuadrado.setText("Lado debe ser mayor a 0");
                txtPerimetroCuadrado.setText("Lado debe ser mayor a 0");
            }else{
                square.setSide(lado);
                txtAreaCuadrado.setText("" + square.calculateArea());
                txtPerimetroCuadrado.setText("" + square.calculatePerimeter());
            }
        }catch(NumberFormatException e){
            txtAreaCuadrado.setText("Tipo de dato no válido");
            txtPerimetroCuadrado.setText("Tipo de dato no válido"); 
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnRegresarMenuCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuCuadradoActionPerformed
        GUIMenu abrir = new GUIMenu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarMenuCuadradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISquare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISquare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISquare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISquare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISquare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelCuadrado;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnRegresarMenuCuadrado;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelFormularioCuadrado;
    private javax.swing.JPanel jPanelbuttonsCuadrado;
    private javax.swing.JLabel lblAreaCuadrado;
    private javax.swing.JLabel lblLadoCuadrado;
    private javax.swing.JLabel lblPerimetroCuadrado;
    private javax.swing.JTextField txtAreaCuadrado;
    private javax.swing.JTextField txtLadoCuadrado;
    private javax.swing.JTextField txtPerimetroCuadrado;
    // End of variables declaration//GEN-END:variables
}
