/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unicauca.figures.presentation;

import com.unicauca.figures.domain.model.Triangle;

/**
 *
 * @author 
 */
public class GUITriangle extends javax.swing.JFrame {

     private Triangle triangle;
    /**
     * Creates new form GUITriangle
     */
    public GUITriangle() {
        initComponents();
        triangle = new Triangle(1,1,1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelTriangulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCalcularTriangulo = new javax.swing.JButton();
        btnRegresarMenuTrian = new javax.swing.JButton();
        jPanelFormulario = new javax.swing.JPanel();
        lblBaseTriangulo = new javax.swing.JLabel();
        txtLado1Trian = new javax.swing.JTextField();
        lblLado2Trian = new javax.swing.JLabel();
        txtLado2Trian = new javax.swing.JTextField();
        lblLado3Trian = new javax.swing.JLabel();
        txtLado3Trian = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        lblPerimetro = new javax.swing.JLabel();
        txtPerimetro = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTriangulo.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabelTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTriangulo.setText("TRIANGULO");
        getContentPane().add(jLabelTriangulo, java.awt.BorderLayout.PAGE_START);

        btnCalcularTriangulo.setText("Calcular");
        btnCalcularTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTrianguloActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcularTriangulo);

        btnRegresarMenuTrian.setText("Regresar al menú");
        btnRegresarMenuTrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuTrianActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarMenuTrian);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanelFormulario.setLayout(new java.awt.GridLayout(5, 2));

        lblBaseTriangulo.setText("Lado 1");
        jPanelFormulario.add(lblBaseTriangulo);
        jPanelFormulario.add(txtLado1Trian);

        lblLado2Trian.setText("Lado 2");
        jPanelFormulario.add(lblLado2Trian);
        jPanelFormulario.add(txtLado2Trian);

        lblLado3Trian.setText("Lado 3");
        jPanelFormulario.add(lblLado3Trian);
        jPanelFormulario.add(txtLado3Trian);

        lblArea.setText("Area");
        jPanelFormulario.add(lblArea);
        jPanelFormulario.add(txtArea);

        lblPerimetro.setText("Perimetro");
        jPanelFormulario.add(lblPerimetro);
        jPanelFormulario.add(txtPerimetro);

        getContentPane().add(jPanelFormulario, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTrianguloActionPerformed
        try{
            double lado1 = Double.parseDouble(txtLado1Trian.getText());
            double lado2 = Double.parseDouble(txtLado2Trian.getText());
            double lado3 = Double.parseDouble(txtLado3Trian.getText());
            if(lado1 <= 0 || lado2 <= 0 || lado3 <= 0){
                txtArea.setText("Lados deben ser mayores a 0");
                txtPerimetro.setText("Lados deben ser mayores a 0");
            }else{
                triangle.setBase(lado1);
                triangle.setSide2(lado2);
                triangle.setSide3(lado3);
                txtArea.setText("" + triangle.calculateArea());
                txtPerimetro.setText("" + triangle.calculatePerimeter());
            }
        }catch(NumberFormatException e){
            txtArea.setText("Tipo de dato no válido");
            txtPerimetro.setText("Tipo de dato no válido");
        }
    }//GEN-LAST:event_btnCalcularTrianguloActionPerformed

    private void btnRegresarMenuTrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuTrianActionPerformed
        GUIMenu abrir = new GUIMenu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarMenuTrianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITriangle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularTriangulo;
    private javax.swing.JButton btnRegresarMenuTrian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTriangulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblBaseTriangulo;
    private javax.swing.JLabel lblLado2Trian;
    private javax.swing.JLabel lblLado3Trian;
    private javax.swing.JLabel lblPerimetro;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtLado1Trian;
    private javax.swing.JTextField txtLado2Trian;
    private javax.swing.JTextField txtLado3Trian;
    private javax.swing.JTextField txtPerimetro;
    // End of variables declaration//GEN-END:variables
}
